-- Crear la base de datos
CREATE DATABASE BDD_INTERNEXO;

-- (Conéctate a la base de datos BDD_INTERNEXO antes de ejecutar el resto del script)

-- Tabla PERSON
CREATE TABLE MGMT_PERSON (
    ID_MGMT_PERSON SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(20) NOT NULL,
    AGE INT NOT NULL,
    IDENTIFICATION VARCHAR(50) NOT NULL,
    ADDRESS VARCHAR(200),
    PHONE VARCHAR(20),
    CONSTRAINT UK_MGMT_PERSON_IDENTIFICATION UNIQUE (IDENTIFICATION),
    CONSTRAINT CHK_MGMT_PERSON_AGE CHECK (AGE > 0)
);

-- Tabla CUSTOMER
CREATE TABLE MGMT_CUSTOMER (
    ID_MGMT_CUSTOMER SERIAL PRIMARY KEY,
    ID_MGMT_PERSON INT NOT NULL,
    CUSTOMER_ID VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(100) NOT NULL,
    STATE BOOLEAN NOT NULL,
    CONSTRAINT UK_MGMT_CUSTOMER_CUSTOMER_ID UNIQUE (CUSTOMER_ID),
    CONSTRAINT FK_MGMT_CUSTOMER_MGMT_PERSON_01 FOREIGN KEY (ID_MGMT_PERSON) REFERENCES MGMT_PERSON(ID_MGMT_PERSON)
);

-- Tabla ACCOUNT
CREATE TABLE MGMT_ACCOUNT (
    ID_MGMT_ACCOUNT SERIAL PRIMARY KEY,
    ACCOUNT_NUMBER VARCHAR(30) NOT NULL,
    ACCOUNT_TYPE VARCHAR(30) NOT NULL,
    INITIAL_BALANCE NUMERIC(15,2) NOT NULL,
    STATE BOOLEAN NOT NULL,
    ID_MGMT_CUSTOMER INT NOT NULL,
    CONSTRAINT UK_MGMT_ACCOUNT_ACCOUNT_NUMBER UNIQUE (ACCOUNT_NUMBER),
    CONSTRAINT FK_MGMT_ACCOUNT_MGMT_CUSTOMER_01 FOREIGN KEY (ID_MGMT_CUSTOMER) REFERENCES MGMT_CUSTOMER(ID_MGMT_CUSTOMER)
);

-- Tabla TRANSACTION
CREATE TABLE MGMT_TRANSACTION (
    ID_MGMT_TRANSACTION SERIAL PRIMARY KEY,
    TRANSACTION_DATE TIMESTAMP NOT NULL,
    TRANSACTION_TYPE VARCHAR(30) NOT NULL,
    AMOUNT NUMERIC(15,2) NOT NULL,
    BALANCE NUMERIC(15,2) NOT NULL,
    ID_MGMT_ACCOUNT INT NOT NULL,
    CONSTRAINT FK_MGMT_TRANSACTION_MGMT_ACCOUNT_01 FOREIGN KEY (ID_MGMT_ACCOUNT) REFERENCES MGMT_ACCOUNT(ID_MGMT_ACCOUNT)
);

-- Índices
CREATE INDEX IDX_MGMT_CUSTOMER_ID_MGMT_PERSON_01 ON MGMT_CUSTOMER(ID_MGMT_PERSON);
CREATE INDEX IDX_MGMT_ACCOUNT_ID_MGMT_CUSTOMER_01 ON MGMT_ACCOUNT(ID_MGMT_CUSTOMER);
CREATE INDEX IDX_MGMT_TRANSACTION_ID_MGMT_ACCOUNT_01 ON MGMT_TRANSACTION(ID_MGMT_ACCOUNT);
